---
- name: Installation de Grafana (VM Supervision)
  hosts: role_SUP
  remote_user: cloudadm
  gather_facts: yes

  tasks:
    - name: Nettoyage complet des résidus Apt Grafana
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/grafana.list
        - /etc/apt/sources.list.d/grafana.sources
      become: yes

    - name: Purge du cache Apt corrompu
      command: apt-get clean
      become: yes

    - name: Installation de gnupg et wget
      apt:
        name: [gnupg, wget]
        state: present
        update_cache: yes
      become: yes

    - name: Création du dossier keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Installation de la clé GPG (méthode de-armored)
      shell: |
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor --yes -o /etc/apt/keyrings/grafana.gpg
      become: yes

    - name: Ajout du dépôt Grafana (Format Moderne)
      copy:
        dest: /etc/apt/sources.list.d/grafana.sources
        content: |
          Types: deb
          URIs: https://apt.grafana.com
          Suites: stable
          Components: main
          Signed-By: /etc/apt/keyrings/grafana.gpg
      become: yes

    - name: Installation de Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes
      become: yes

    - name: Start Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes
      become: yes