---
- name: Configuration des Data Sources Grafana
  hosts: role_SUP
  remote_user: cloudadm
  become: yes
  vars_files:
    - ./vars/secrets.yml

  tasks:
    - name: Ajouter InfluxDB comme source de données (Métriques)
      community.grafana.grafana_datasource:
        name: "InfluxDB-Trix"
        ds_type: "influxdb"
        ds_url: "http://localhost:8086" 
        database: "telegraf"
        grafana_url: "http://localhost:3000"
        grafana_user: "admin"
        grafana_password: "{{ grafana_admin_password }}"
        state: present
        validate_certs: no 

    - name: Ajouter Loki comme source de données (Logs)
      community.grafana.grafana_datasource:
        name: "Loki-Trix"
        ds_type: "loki"
        ds_url: "http://localhost:3100"
        grafana_url: "http://localhost:3000"
        grafana_user: "admin"
        grafana_password: "{{ grafana_admin_password }}"
        state: present