---
- name: Configuration des Data Sources Grafana
  hosts: role_SUP
  remote_user: cloudadm
  become: yes
  vars_files:
    - ./vars/secrets.yml

  tasks:
    - name: Ajouter InfluxDB comme source de données (Métriques)
      community.grafana.grafana_datasource:
        name: "InfluxDB-Trix"
        ds_type: "influxdb"
        url: "http://localhost:8086"
        database: "telegraf" # Nom de la DB créée par Telegraf
        user: "admin"        # Si tu as activé l'auth InfluxDB
        password: "{{ influxdb_password | default('') }}"
        grafana_url: "http://localhost:3000"
        url_username: "admin"
        url_password: "{{ grafana_admin_password }}"

    - name: Ajouter Loki comme source de données (Logs)
      community.grafana.grafana_datasource:
        name: "Loki-Trix"
        ds_type: "loki"
        url: "http://localhost:3100"
        grafana_url: "http://localhost:3000"
        url_username: "admin"
        url_password: "{{ grafana_admin_password }}"