{
 "title": "Dashboard-TEST",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"host\""
    }
   }
  ]
 },
 "panels": [
  { "title": "APPLI STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"result_code\") FROM \"http_response\" WHERE (\"type\" = 'app_internal') AND $timeFilter"
    }
   ]
  },
  { "title": "HTTPS STATUS", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 } },
  {
   "title": "Logs APPLI",
   "type": "logs",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"systemd-journal\", unit=\"timeapp.service\"}"
    },
    {
     "direction": "backward",
     "expr": "{job=\"systemd-journal\", unit=\"nginx.service\"}"
    }
   ]
  },
  { "title": "Metrics VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "SELECT mean(\"usage_system\") + mean(\"usage_user\") FROM \"cpu\" WHERE \"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE \"path\" = '/' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Kibits" } },
   "targets": [
    {
     "alias": "$tag_host.",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) * 8 FROM \"net\" WHERE \"interface\" != 'lo' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)"
    }
   ]
  }
 ]
}