---
- name: Configuration appli web
  hosts: role_APPLI
  remote_user: cloudadm
  gather_facts: yes
  vars:
    app_dir: /srv/timeapp
    app_user: www-data
    app_group: www-data
    venv_path: "{{ app_dir }}/venv"
    db_path: "{{ app_dir }}/stats.db"

  tasks:
    - name: Installation python3 et firewall
      apt:
        name: 
          - python3-pip
          - python3-venv
          - python3-full
          - iptables-persistent
        state: present
        update_cache: yes
      become: yes

    - name: Installation Gunicorn et BDD
      pip:
        name:
          - flask
          - gunicorn
          - flask-sqlalchemy
        virtualenv: "{{ venv_path }}"
        virtualenv_command: python3 -m venv
      become: yes

    - name: Creation du répertoire applicatif
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0775' # On donne les droits d'écriture pour SQLite
      become: yes
    
    - name: Deployement code python
      copy:
        dest: "{{ app_dir }}/app.py"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
        content: |
          import os
          from flask import Flask, jsonify
          from datetime import datetime
          from flask_sqlalchemy import SQLAlchemy

          app = Flask(__name__)
          basedir = os.path.abspath(os.path.dirname(__file__))
          app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'stats.db')
          app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

          db = SQLAlchemy(app)

          class Visit(db.Model):
              id = db.Column(db.Integer, primary_key=True)
              date = db.Column(db.DateTime, default=datetime.utcnow)
          
          with app.app_context():
              db.create_all()

          @app.route('/')
          def index():
              new_visit = Visit()
              db.session.add(new_visit)
              db.session.commit()
              count = Visit.query.count()
              now = datetime.now().strftime("%H:%M:%S")
              return f"<h1>Heure : {now}</h1><hr><p>Vue <strong>{count}</strong> fois.</p>"

          if __name__ == "__main__":
              app.run(host='0.0.0.0')
      become: yes
      notify: Restart TimeApp

    - name: Creation service Systemd
      copy:
        dest: /etc/systemd/system/timeapp.service
        content: |
          [Unit]
          Description=Gunicorn for TimeApp
          After=network.target

          [Service]
          User={{ app_user }}
          Group={{ app_group }}
          WorkingDirectory={{ app_dir }}
          ExecStart={{ venv_path }}/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 --access-logfile - --error-logfile - app:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
      become: yes
      notify: Restart TimeApp

    - name: Activation du Service TimeApp
      systemd:
        name: timeapp
        state: started
        enabled: yes
        daemon_reload: yes
      become: yes

    - name: Anti-Lockout (Remettre en accept par defaut)
      iptables:
        chain: INPUT
        policy: ACCEPT
      become: yes

    - name : Vider les règles existantes
      iptables:
        chain: INPUT
        flush: yes
      become: yes

    - name: Autorisation du trafic local (Loopback)
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
      become: yes

    - name: Autorisation des connexions dejà établies
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      become: yes

    - name: Autorisation Ports SSH et App
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop: [ '22', '8000' ]
      become: yes

    - name: Passage de la politique INPUT en DROP
      iptables: 
        chain: INPUT
        policy: DROP
      become: yes

    - name: Sauvegarde permanente de iptables
      shell: netfilter-persistent save
      become: yes

  handlers:
    - name: Restart TimeApp
      systemd:
        name: timeapp
        state: restarted
      become: yes