ansible_user: cloudadm
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Configuration de rebond dynamique
ansible_ssh_common_args : >
  {% if inventory_hostname != '01-SRV-BAST-TRIX' %}
  -o ProxyJump=cloudadm@{{ hostvars['01-SRV-BAST-TRIX']['ansible_host'] }}
  {% endif %}

ansible_become: yes
ansible_become_method: sudo
ansible_become_password: "{{ cloudadm_password_secret }}"