---
- name : Restriction de l'accès SSH au Bastion uniquement
  hosts: role_ALL:!role_BAST
  remote_user: cloudadm
  become: yes
  vars:
    bastion_ip: "10.60.11.25"

  tasks:  
    - name: Configurer SSH pour n'accepter que le Bastion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowUsers'
        line: "AllowUsers cloudadm@{{ bastion_ip }}"
        state: present
        #validate: '/usr/sbin/sshd -t'
      notify: Restart SSH
      
    
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted