---
- name: Restriction de l'accès SSH au Bastion uniquement
  hosts: "role_ALL:!role_BAST"
  remote_user: cloudadm
  become: yes

  tasks:  
    - name: Configurer SSH pour n'accepter que le Bastion
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowUsers'
        # On récupère l'IP du premier hôte du groupe role_BAST
        line: "AllowUsers cloudadm@{{ hostvars[groups['role_BAST'][0]]['ansible_host'] }}"
        state: present
      notify: Restart SSH
      
  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted