---
- name: Configuration du Reverse Proxy
  hosts: role_RVPRX
  remote_user: cloudadm
  gather_facts: yes

  tasks:
    - name: Installation de Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes

    - name: Déploiement de la configuration Reverse Proxy
      template:
        src: templates/reverse_proxy.conf.j2
        dest: /etc/nginx/sites-available/reverse_proxy.conf
      become: yes

    - name: Activation de la configuration
      file:
        src: /etc/nginx/sites-available/reverse_proxy.conf
        dest: /etc/nginx/sites-enabled/reverse_proxy.conf
        state: link
      become: yes

    - name: Suppression de la configuration par défaut de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes

    - name: Redémarrage de Nginx
      service:
        name: nginx
        state: restarted
      become: yes